# Generated by Django 5.0.3 on 2024-04-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='currentTemperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('windSpeed', models.FloatField(default=0)),
                ('windDirection', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('uvIndex', models.FloatField(default=0)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='widget.station')),
            ],
        ),
    ]
