# Generated by Django 5.0.3 on 2024-04-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0003_alter_station_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='currentTemperature',
        ),
    ]
